# Generated by Django 5.2.3 on 2025-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(default="", max_length=50)),
                ("task_type", models.TextField(default="", max_length=50)),
                ("image", models.TextField(default="")),
                ("predictions", models.TextField(default="")),
                ("version_code", models.IntegerField(default=0)),
                ("status", models.CharField(default="Unknown", max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
